"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServerPackets = void 0;
var ServerPackets;
(function (ServerPackets) {
    ServerPackets[ServerPackets["CHAT"] = 0] = "CHAT";
    ServerPackets[ServerPackets["CAMERA"] = 1] = "CAMERA";
    ServerPackets[ServerPackets["MOVEMENT"] = 2] = "MOVEMENT";
    ServerPackets[ServerPackets["ANGLE"] = 3] = "ANGLE";
    ServerPackets[ServerPackets["ATTACK"] = 4] = "ATTACK";
    ServerPackets[ServerPackets["INTERACTION"] = 5] = "INTERACTION";
    ServerPackets[ServerPackets["DROP_ONE_ITEM"] = 6] = "DROP_ONE_ITEM";
    ServerPackets[ServerPackets["CRAFT"] = 7] = "CRAFT";
    ServerPackets[ServerPackets["GIVE_ITEM"] = 8] = "GIVE_ITEM";
    ServerPackets[ServerPackets["TAKE_ITEM"] = 9] = "TAKE_ITEM";
    ServerPackets[ServerPackets["BUILD"] = 10] = "BUILD";
    ServerPackets[ServerPackets["GET_FOCUS"] = 11] = "GET_FOCUS";
    ServerPackets[ServerPackets["GIVE_FURNACE"] = 12] = "GIVE_FURNACE";
    ServerPackets[ServerPackets["PING"] = 13] = "PING";
    ServerPackets[ServerPackets["STOP_ATTACK"] = 14] = "STOP_ATTACK";
    ServerPackets[ServerPackets["UNLOCK_CHEST"] = 15] = "UNLOCK_CHEST";
    ServerPackets[ServerPackets["LOCK_CHEST"] = 16] = "LOCK_CHEST";
    ServerPackets[ServerPackets["RESURRECTION"] = 17] = "RESURRECTION";
    ServerPackets[ServerPackets["JOIN_TEAM"] = 18] = "JOIN_TEAM";
    ServerPackets[ServerPackets["LEAVE_TEAM"] = 19] = "LEAVE_TEAM";
    ServerPackets[ServerPackets["KICK_TEAM"] = 20] = "KICK_TEAM";
    ServerPackets[ServerPackets["CHOOSE_KIT"] = 21] = "CHOOSE_KIT";
    ServerPackets[ServerPackets["GIVE_WHEAT"] = 22] = "GIVE_WHEAT";
    ServerPackets[ServerPackets["TAKE_FLOUR"] = 23] = "TAKE_FLOUR";
    ServerPackets[ServerPackets["GIVE_FLOUR_OVEN"] = 24] = "GIVE_FLOUR_OVEN";
    ServerPackets[ServerPackets["GIVE_WOOD_OVEN"] = 25] = "GIVE_WOOD_OVEN";
    ServerPackets[ServerPackets["TAKE_BREAD_OVEN"] = 26] = "TAKE_BREAD_OVEN";
    ServerPackets[ServerPackets["CLAIM_QUEST_REWARD"] = 27] = "CLAIM_QUEST_REWARD";
    ServerPackets[ServerPackets["DROP_ITEM"] = 28] = "DROP_ITEM";
    ServerPackets[ServerPackets["RECYCLE_START"] = 29] = "RECYCLE_START";
    ServerPackets[ServerPackets["GIVE_WELL"] = 30] = "GIVE_WELL";
    ServerPackets[ServerPackets["CANCEL_CRAFT"] = 31] = "CANCEL_CRAFT";
    ServerPackets[ServerPackets["MARKET"] = 32] = "MARKET";
    ServerPackets[ServerPackets["LOCK_TEAM"] = 33] = "LOCK_TEAM";
    ServerPackets[ServerPackets["CONSOLE"] = 34] = "CONSOLE";
    ServerPackets[ServerPackets["TAKE_EXTRACTOR"] = 35] = "TAKE_EXTRACTOR";
    ServerPackets[ServerPackets["GIVE_WOOD_EXTRACTOR"] = 36] = "GIVE_WOOD_EXTRACTOR";
})(ServerPackets || (exports.ServerPackets = ServerPackets = {}));
