"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AnimalBoxes = void 0;
const EntityType_1 = require("./types/EntityType");
const Cosmetics_1 = require("./Cosmetics");
exports.AnimalBoxes = [];
exports.AnimalBoxes[EntityType_1.EntityType.WOLF] = Cosmetics_1.BOX.BOX_OF_THE_WOLF;
exports.AnimalBoxes[EntityType_1.EntityType.RABBIT] = Cosmetics_1.BOX.BOX_OF_THE_RABBIT;
exports.AnimalBoxes[EntityType_1.EntityType.SPIDER] = Cosmetics_1.BOX.BOX_OF_THE_SPIDER;
exports.AnimalBoxes[EntityType_1.EntityType.HAWK] = Cosmetics_1.BOX.BOX_OF_THE_HAWK;
exports.AnimalBoxes[EntityType_1.EntityType.BOAR] = Cosmetics_1.BOX.BOX_OF_THE_BOAR;
exports.AnimalBoxes[EntityType_1.EntityType.CRAB] = Cosmetics_1.BOX.BOX_OF_THE_CRAB;
exports.AnimalBoxes[EntityType_1.EntityType.CRAB_BOSS] = Cosmetics_1.BOX.BOX_OF_THE_KING_CRAB;
exports.AnimalBoxes[EntityType_1.EntityType.FOX] = Cosmetics_1.BOX.BOX_OF_THE_FOX;
exports.AnimalBoxes[EntityType_1.EntityType.BEAR] = Cosmetics_1.BOX.BOX_OF_THE_BEAR;
exports.AnimalBoxes[EntityType_1.EntityType.PENGUIN] = Cosmetics_1.BOX.BOX_OF_THE_PENGUIN;
exports.AnimalBoxes[EntityType_1.EntityType.MAMMOTH] = Cosmetics_1.BOX.BOX_OF_THE_MAMMOTH;
exports.AnimalBoxes[EntityType_1.EntityType.BABY_MAMMOTH] = Cosmetics_1.BOX.BOX_OF_THE_BABY_MAMMOTH;
exports.AnimalBoxes[EntityType_1.EntityType.DRAGON] = Cosmetics_1.BOX.BOX_OF_THE_DRAGON;
exports.AnimalBoxes[EntityType_1.EntityType.BABY_DRAGON] = Cosmetics_1.BOX.BOX_OF_THE_BABY_DRAGON;
exports.AnimalBoxes[EntityType_1.EntityType.FLAME] = Cosmetics_1.BOX.BOX_OF_THE_FIRE_MOB;
exports.AnimalBoxes[EntityType_1.EntityType.LAVA_DRAGON] = Cosmetics_1.BOX.BOX_OF_THE_LAVA_DRAGON;
exports.AnimalBoxes[EntityType_1.EntityType.BABY_LAVA] = Cosmetics_1.BOX.BOX_OF_THE_BABY_LAVA;
exports.AnimalBoxes[EntityType_1.EntityType.VULTURE] = Cosmetics_1.BOX.BOX_OF_THE_VULTURE;
exports.AnimalBoxes[EntityType_1.EntityType.SAND_WORM] = Cosmetics_1.BOX.BOX_OF_THE_SANDWORM;
exports.AnimalBoxes[EntityType_1.EntityType.PIRANHA] = Cosmetics_1.BOX.BOX_OF_THE_PIRANHA;
exports.AnimalBoxes[EntityType_1.EntityType.KRAKEN] = Cosmetics_1.BOX.BOX_OF_THE_KRAKEN;
