export enum ServerPackets {
    CHAT,
    CAMERA,
    MOVEMENT,
    ANGLE,
    ATTACK,
    INTERACTION,
    DROP_ONE_ITEM,
    CRAFT,
    GIVE_ITEM,
    TAKE_ITEM,
    BUILD,
    STOP_ATTACK = 14,
    LOCK_CHEST = 16,
    DROP_ITEM = 28,
    RECYCLE_START,
    GIVE_WELL,
    CANCEL_CRAFT,
    MARKET,
    CONSOLE = 36
}
